"""added url test

Revision ID: 01e522e4d525
Revises: 02fcee34a3ec
Create Date: 2021-08-03 09:52:16.464624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e522e4d525'
down_revision = '02fcee34a3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'url')
    # ### end Alembic commands ###
